### ISSUE TITLE
3.6 fails on tests

### ISSUE THREAD

**Issue by ftrias** [ftrias/TeensyThreads#1]
on a 3.6 get "Error while setting serial port parameters: 115,200 N 8 1" everytime the sketch tries to print to TeensyMonitor. Running 1.8.0 on Windows 10.

Oddly enough the "Print" example works on the 3.6.

**Comment by mjs513** [comment]
Getting a similar error on 3.5: "Error while setting serial port parameters: 9,600 N 8 1".  Running 1.6.12 on Windows 10.  As ftrias says the "Print" example works on the 3.5 as well.

**Comment by ftrias** [comment]
Issue fixed
