### ISSUE TITLE
Teensy 4 timeslice 5 ms

### ISSUE THREAD

**Issue by manitou48** [ftrias/TeensyThreads#20]
With scope I noticed that Teensy 3* threads have 10 ms timeslice, but Teensy 4 has 5 ms timeslice?

I think the problem is that GPT ISR will fire twice unless you have 
**asm volatile ("dsb");**
at the end of the isr.

static void __attribute((naked, noinline)) gpt1_isr() {
  GPT1_SR |= GPT_SR_OF1;  // clear set bit
  __asm volatile("dsb");
  __asm volatile("b context_switch");
}

**Comment by ftrias** [comment]
Thanks for catching that. It's a subtle bug. I have commited your suggested fix.
