### ISSUE TITLE
License Info

### ISSUE THREAD

**Issue by PaulStoffregen** [ftrias/TeensyThreads#3]
I've heard several requires to include this library with the Teensyduino installer.  The only blocking issue is lack of open source license info.

Would you be willing to use the MIT license?  That's the same one used for most other Teensy library code.

https://opensource.org/licenses/MIT

**Comment by ftrias** [comment]
The license is on my todo. I was thinking of using a GNU license. Would
that work? Or do you strongly prefer the MIT license.

**Comment by PaulStoffregen** [comment]
I personally prefer to see the MIT license.

**Comment by ftrias** [comment]
Thanks. I added the MIT license to the files in github so you can do with
it as you please.
